# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-connect'
    subscriptionId: '360e3df8-125e-4f0e-9f6e-8b3cd87d9d88'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Mikecloud24/cicdARMRepo/refs/heads/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName cicdARMPro'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'